VERSION 2.00
Begin Form FrmMap 
   Caption         =   "U.S.   Nuclear   Power   Plants"
   ClientHeight    =   5100
   ClientLeft      =   450
   ClientTop       =   1920
   ClientWidth     =   9195
   Height          =   5505
   Left            =   390
   LinkTopic       =   "Form1"
   ScaleHeight     =   5100
   ScaleWidth      =   9195
   Top             =   1575
   Width           =   9315
   Begin OptionButton Option33 
      Caption         =   "Option33"
      Height          =   255
      Left            =   7680
      TabIndex        =   33
      Top             =   2640
      Width           =   375
   End
   Begin OptionButton Option32 
      Caption         =   "Option32"
      Height          =   255
      Left            =   6600
      TabIndex        =   32
      Top             =   3600
      Width           =   255
   End
   Begin OptionButton Option31 
      Caption         =   "Option31"
      Height          =   255
      Left            =   8400
      TabIndex        =   31
      Top             =   1440
      Width           =   255
   End
   Begin OptionButton Option30 
      Caption         =   "Option30"
      Height          =   255
      Left            =   8280
      TabIndex        =   30
      Top             =   1680
      Width           =   255
   End
   Begin OptionButton Option29 
      Caption         =   "Option29"
      Height          =   255
      Left            =   8040
      TabIndex        =   29
      Top             =   1920
      Width           =   255
   End
   Begin OptionButton Option28 
      Caption         =   "Option28"
      Height          =   255
      Left            =   7680
      TabIndex        =   28
      Top             =   2280
      Width           =   255
   End
   Begin OptionButton Option27 
      Caption         =   "Option27"
      Height          =   255
      Left            =   7800
      TabIndex        =   27
      Top             =   1440
      Width           =   255
   End
   Begin OptionButton Option26 
      Caption         =   "Option26"
      Height          =   255
      Left            =   7320
      TabIndex        =   26
      Top             =   1800
      Width           =   255
   End
   Begin OptionButton Option25 
      Caption         =   "Option25"
      Height          =   255
      Left            =   8280
      TabIndex        =   25
      Top             =   1080
      Width           =   255
   End
   Begin OptionButton Option24 
      Caption         =   "Option24"
      Height          =   255
      Left            =   8760
      TabIndex        =   24
      Top             =   720
      Width           =   255
   End
   Begin OptionButton Option23 
      Caption         =   "Option23"
      Height          =   255
      Left            =   7440
      TabIndex        =   23
      Top             =   3360
      Width           =   255
   End
   Begin OptionButton Option22 
      Caption         =   "Option22"
      Height          =   255
      Left            =   7440
      TabIndex        =   22
      Top             =   2880
      Width           =   255
   End
   Begin OptionButton Option21 
      Caption         =   "Option21"
      Height          =   255
      Left            =   6960
      TabIndex        =   21
      Top             =   3000
      Width           =   255
   End
   Begin OptionButton Option20 
      Caption         =   "Option20"
      Height          =   255
      Left            =   6720
      TabIndex        =   20
      Top             =   2280
      Width           =   255
   End
   Begin OptionButton Option19 
      Caption         =   "Option19"
      Height          =   255
      Left            =   6600
      TabIndex        =   19
      Top             =   1440
      Width           =   255
   End
   Begin OptionButton Option18 
      Caption         =   "Option18"
      Height          =   255
      Left            =   6240
      TabIndex        =   18
      Top             =   3000
      Width           =   255
   End
   Begin OptionButton Option17 
      Caption         =   "Option17"
      Height          =   255
      Left            =   7320
      TabIndex        =   17
      Top             =   3840
      Width           =   255
   End
   Begin OptionButton Option16 
      Caption         =   "Option16"
      Height          =   255
      Left            =   6120
      TabIndex        =   16
      Top             =   3600
      Width           =   255
   End
   Begin OptionButton Option15 
      Caption         =   "Option15"
      Height          =   255
      Left            =   5880
      TabIndex        =   15
      Top             =   2040
      Width           =   255
   End
   Begin OptionButton Option14 
      Caption         =   "Option14"
      Height          =   255
      Left            =   5880
      TabIndex        =   14
      Top             =   1200
      Width           =   255
   End
   Begin OptionButton Option13 
      Caption         =   "Option13"
      Height          =   255
      Left            =   5640
      TabIndex        =   13
      Top             =   3840
      Width           =   255
   End
   Begin OptionButton Option12 
      Caption         =   "Option12"
      Height          =   255
      Left            =   5400
      TabIndex        =   12
      Top             =   3360
      Width           =   255
   End
   Begin OptionButton Option11 
      Caption         =   "Option11"
      Height          =   255
      Left            =   5400
      TabIndex        =   11
      Top             =   2280
      Width           =   255
   End
   Begin OptionButton Option10 
      Caption         =   "Option10"
      Height          =   255
      Left            =   5160
      TabIndex        =   10
      Top             =   1680
      Width           =   255
   End
   Begin OptionButton Option9 
      Caption         =   "Option9"
      Height          =   255
      Left            =   5280
      TabIndex        =   9
      Top             =   1200
      Width           =   255
   End
   Begin OptionButton Option8 
      Caption         =   "Option8"
      Height          =   255
      Left            =   4200
      TabIndex        =   8
      Top             =   2040
      Width           =   255
   End
   Begin OptionButton Option7 
      Caption         =   "Option7"
      Height          =   255
      Left            =   3000
      TabIndex        =   7
      Top             =   2400
      Width           =   255
   End
   Begin OptionButton Option6 
      Caption         =   "Option6"
      Height          =   255
      Left            =   4320
      TabIndex        =   6
      Top             =   3720
      Width           =   255
   End
   Begin OptionButton Option5 
      Caption         =   "Option5"
      Height          =   255
      Left            =   4800
      TabIndex        =   5
      Top             =   2400
      Width           =   255
   End
   Begin OptionButton Option4 
      Caption         =   "Option4"
      Height          =   255
      Left            =   1440
      TabIndex        =   4
      Top             =   2880
      Width           =   255
   End
   Begin OptionButton Option3 
      Caption         =   "Option3"
      Height          =   255
      Left            =   1200
      TabIndex        =   3
      Top             =   1200
      Width           =   255
   End
   Begin OptionButton Option2 
      Caption         =   "Option2"
      Height          =   255
      Left            =   1440
      TabIndex        =   2
      Top             =   720
      Width           =   255
   End
   Begin OptionButton Option1 
      Caption         =   "Option1"
      Height          =   255
      Left            =   840
      TabIndex        =   1
      Top             =   2400
      Width           =   255
   End
   Begin CommandButton Command1 
      Caption         =   "Exit"
      Height          =   375
      Left            =   7680
      TabIndex        =   0
      Top             =   240
      Width           =   615
   End
   Begin Image Image2 
      Height          =   5040
      Left            =   0
      Picture         =   FRMMAP.FRX:0000
      Top             =   0
      Width           =   9600
   End
   Begin Image Image1 
      Height          =   5415
      Left            =   120
      Top             =   0
      Width           =   8895
   End
End

Sub Command1_Click ()
Unload Me
End Sub

Sub Form_Unload (Cancel As Integer)
Unload Me
End Sub

Sub Option1_Click ()

MsgBox "Diablo Canyon1,2; " & NL & "San Onofre 2,3 ", 48, "CALIFORNIA"
End Sub

Sub Option10_Click ()
MsgBox "Duane Arnold", 48, "Iowa"

End Sub

Sub Option11_Click ()
MsgBox "Calloway", 48, "Missouri"
End Sub

Sub Option12_Click ()
MsgBox "Arkansas 1,2 ", 48, "Arkansas"
End Sub

Sub Option13_Click ()
MsgBox "River Bend", 48, "Lousiana"
End Sub

Sub Option14_Click ()
MsgBox "Point Beach 1, 2", 48, " WISCONSON"
End Sub

Sub Option15_Click ()
MsgBox "Braidwood 1, 2" & NL & "Byron 1, 2" & NL & "Dresden 2, 3" & NL & "LaSalle County 1, 2" & NL & "Quad Cities 1, 2" & NL & "Zion 1, 2", 48, "Illinois"
End Sub

Sub Option16_Click ()
MsgBox "Joseph M. Farley 1, 2" & NL & "Bellefonte 1,2" & NL & "Browns Ferry 1, 2, 3", 48, "ALABAMA"
End Sub

Sub Option17_Click ()
MsgBox "St. Lucie 1, 2" & NL & "Turkey Point 3, 4" & NL & "Crystal River 3", 48, "FLORIDA"
End Sub

Sub Option18_Click ()
MsgBox "Sequoyah 1, 2" & NL & "Watts Bar 1, 2", 48, "TENNESSEE"
End Sub

Sub Option19_Click ()
MsgBox "Donald C. Cook 1, 2" & NL & "Fermi 2" & NL & "Big Rock" & NL & "Palisades", 48, "MICHIGAN"
End Sub

Sub Option2_Click ()
MsgBox "WNP 1, 2, 3", 48, "WASHINGTON"
End Sub

Sub Option20_Click ()
MsgBox "Davis Besse", 48, "OHIO"
End Sub

Sub Option21_Click ()
MsgBox "Edwin I. Hatch 1, 2" & NL & "Alvin W. Vogtle 1, 2", 48, "GEORGIA"
End Sub

Sub Option22_Click ()
MsgBox "McGuire 1, 2" & NL & "Bruinswick 1, 2" & NL & "Shearan Harris", 48, "NORTH CAROLINA"
End Sub

Sub Option23_Click ()
MsgBox "Robinson 2" & NL & "Catawba 1, 2" & NL & "Oconee 1, 2, 3", 48, "SOUTH CAROLINA"
End Sub

Sub Option24_Click ()
MsgBox "Maine Yankee", 48, "MAINE"
End Sub

Sub Option25_Click ()
MsgBox "Vermont Yankee", 48, "VERMONT"
End Sub

Sub Option26_Click ()
MsgBox "Three Mile Island 1" & NL & "Beaver Valley 1, 2" & NL & "Limerick 1,2" & NL & "Peachbottom 2, 3" & NL & "Susquehanna 1,2", 48, "PENNSYLVANIA"
End Sub

Sub Option27_Click ()
MsgBox "R. E. Ginna" & NL & "Indian Point 2, 3" & NL & "Nine Mile Point 1, 2" & NL & "JamesA. Fitzpatrick", 48, "NEW YORK"
End Sub

Sub Option28_Click ()
MsgBox "Calvert Cliffs 1, 2", 48, "MARYLAND"
End Sub

Sub Option29_Click ()
MsgBox "Oyster Creek" & NL & "Salem 1, 2" & NL & "Hope Creek", 48, "NEW JERSEY"
End Sub

Sub Option3_Click ()
MsgBox " ", 48, "OREGON"
End Sub

Sub Option30_Click ()
MsgBox "Haddam Neck", 48, "CONNECTICUT"
End Sub

Sub Option31_Click ()
MsgBox "Piligram", 48, "MASSACHUSETTS"
End Sub

Sub Option32_Click ()
MsgBox "Grand Gulf", 48, "MISSISSIPPI"
End Sub

Sub Option33_Click ()
MsgBox "North Anna 1, 2" & NL & "Surrey 1, 2", 48, "VIRGINIA"
End Sub

Sub Option4_Click ()
MsgBox "Palo Verde 1, 2, 3", 48, "ARIZONIA"
End Sub

Sub Option5_Click ()
MsgBox "Wolf Creek", 48, "KANSAS"
End Sub

Sub Option6_Click ()
MsgBox "Commanche Peak 1, 2", 48, "TEXAS"
End Sub

Sub Option7_Click ()
MsgBox " ", 48, "COLORODO"
End Sub

Sub Option8_Click ()
MsgBox "Fort Calhoun", 48, "NEBRASKA"
End Sub

Sub Option9_Click ()
   MsgBox "Prairie Isalnd 1, 2" & NL & "Monticello", 48, "MINNASOTA"
End Sub

