// Part I - front matter and the physics chapters.
// Block descriptors are rendered by build.mjs.

export const front = [
  { t: "h1", x: "Preface" },
  { t: "p", x: "The design of a thermal nuclear reactor, together with the power conversion system that turns its heat into electricity, is a complex integration of physics and engineering. It draws on neutron physics, thermal-hydraulics, stability and control, materials science, structural analysis, and radiation shielding. No single calculation settles a reactor concept. Instead, the concept emerges from parametric studies that vary the fundamental choices — fuel, moderator, coolant, geometry, and conversion cycle — and weigh the consequences of each against the design objectives." },
  { t: "p", x: "This manual accompanies DESIGN YOUR OWN NUCLEAR REACTOR, a program first written in 1993 for Windows 3.1 and now rebuilt to run in any web browser. The program is menu-driven. You select materials and a core shape, you enter a handful of operating parameters, and it computes the critical mass of fuel along with the power, power density, heat flux, coolant velocity, fuel temperature, neutron flux, and cycle efficiency that follow from your choices. Results appear both as summary tables and as a live plant diagram. You can accumulate cases and compare them side by side." },
  { t: "p", x: "The calculation is a preliminary conceptual one. It uses the thermal group approximation, the homogeneous reactor approximation, and the Fermi age approximation. It assumes no reflector. The numbers it returns are rough estimates, and they are not as accurate as a Monte Carlo simulation of a heterogeneous core. That limitation is the point. Because each case runs instantly, you can sweep a variable across its whole range and watch what happens, which is how engineering intuition is actually built. A student who runs fifty cases in an afternoon learns more about the shape of the design space than one who runs a single high-fidelity calculation." },
  { t: "p", x: "The manual is organised in three parts. Part I develops the neutron physics that governs criticality. Part II covers the engineering of heat removal and power conversion. Part III is a practical guide to running the program, with four fully worked examples and a chapter on parametric studies. A glossary, a reference list, and six appendices of data close the volume." },
  { t: "p", x: "The program is free to use and requires no installation. Open a browser and go to:" },
  { t: "url", x: "https://reactor-seven.vercel.app/" },
  { t: "pagebreak" },
];

export const part1 = [
  { t: "part", x: "Part I", sub: "The Physics of Thermal Reactors" },

  // ------------------------------------------------------------------ Ch 1
  { t: "h1", x: "1. Introduction and Background" },

  { t: "h2", x: "1.1 The origin of reactor engineering" },
  { t: "p", x: "The development of nuclear reactors began with the atomic programme of the Second World War, the Manhattan Project. Those first reactors were built to produce plutonium for weapons. Commercial development afterwards grew out of the same partnership: the United States, the United Kingdom, France, and Canada." },
  { t: "p", x: "Canada was the first nation to emphasise the civil side. It had hosted major experimental facilities, including the first reactor outside the United States. After the war the British recalled their scientists from Canada to start their own programme, leaving Canada with heavy water production plant and large natural uranium reserves. Canada's NRX research reactor, which went into service in 1947, became the ancestor of the CANDU heavy-water design. The French started their own programme and reached criticality in 1948; by 1956 they had a plutonium-producing reactor that was air-cooled and graphite-moderated. The United Kingdom began with the gas-cooled MAGNOX type, chosen in part because Britain then lacked uranium enrichment capacity." },
  { t: "p", x: "The United States, with abundant coal, oil, and natural gas, felt no urgency about commercial nuclear power and explored many reactor types instead. What eventually forced convergence was the navy: the demand for a compact, reliable reactor for submarines drove the rapid development of the pressurised water reactor. The PWR, and later the boiling water reactor, became the basis of the American commercial industry. Six basic commercial types are in service today: the PWR, the BWR, the CANDU, the gas-cooled MAGNOX, the advanced gas-cooled reactor, and the high-temperature gas reactor." },
  { t: "p", x: "Alongside these are the production reactors, a wide variety of research and test reactors, and space and propulsion reactors: fast reactors, aqueous fuel reactors, molten-salt reactors, and breeders. The variety is not accidental. Each design is the answer to a different question. A reactor optimised to produce electricity cheaply on a large site looks nothing like one optimised for minimum mass in a spacecraft." },

  { t: "h2", x: "1.2 Why design is a parametric problem" },
  { t: "p", x: "Four choices dominate a thermal reactor concept, and each one pulls on the others." },
  { t: "bullets", x: [
    "The fuel sets the probability that a neutron absorbed in the fuel produces a fission, and how many neutrons that fission releases.",
    "The moderator sets the probability that a fast neutron slows to thermal energy without being captured or leaking out.",
    "The geometry and dimensions set the rate at which neutrons are lost through the surface.",
    "The coolant absorbs some neutrons, and it determines how fast heat can be carried out of the core and at what temperature — which in turn fixes the efficiency of the conversion cycle.",
  ]},
  { t: "p", x: "No choice can be made in isolation. Enlarging the core reduces leakage and helps criticality, but it also increases the mass of fuel you must buy and reduces the power density, which may be exactly what you did not want. Choosing graphite as a moderator buys you a very low absorption cross section, but graphite's long Fermi age means neutrons travel far while slowing down, so the core must be large. Raising the coolant outlet temperature raises the cycle efficiency, but it also raises the fuel centreline temperature towards the melting point. Every gain is paid for somewhere." },
  { t: "p", x: "This is what the program is for. It makes the cost of asking \"what if\" close to zero, so you can map the trade surface rather than guess at it." },

  { t: "h2", x: "1.3 What the program computes, and what it does not" },
  { t: "p", x: "Given a fuel, a moderator, a coolant, a core shape and size, and five operating parameters, the program solves for the moderator-to-fuel atom ratio that makes the reactor exactly critical. From that ratio it derives the critical mass of fuel. It then computes the thermal power from the coolant energy balance, and from the power it derives power density, heat flux, fuel centreline temperature, specific power, thermal neutron flux, annual burnup, coolant velocity, Reynolds number, pressure drop, pumping power, secondary flowrate, turbine output, and cycle efficiency." },
  { t: "p", x: "It does not model burnup over time, fission product poisoning, control rod worth, transients, shielding thickness, structural stress, or cost. It assumes the core is homogeneous — fuel and moderator perfectly mixed rather than arranged in pins and lattices — and it assumes no reflector surrounds the core. A real design would use a reflector, which reduces critical mass substantially. Every result should therefore be read as an order-of-magnitude guide with the right sensitivities, not as a number to build from." },
  { t: "callout", title: "A note on the reconstruction", x: "The original 1993 program contained several leftover debugging statements that pinned primary pressure, pump power, and turbine output to fixed constants, and a misplaced conditional that corrupted coolant velocity for every coolant except helium. These have been corrected in the browser version so that the values respond to your design. Everything else — every cross section, every material property table, every correlation — is carried over unchanged from the original source." },

  // ------------------------------------------------------------------ Ch 2
  { t: "h1", x: "2. Fission and the Neutron Life Cycle" },

  { t: "h2", x: "2.1 The fission event" },
  { t: "p", x: "Nuclear fission is the splitting of a heavy nucleus into two fission fragments, accompanied by one to three free neutrons, several gamma rays, and about 200 million electron-volts of energy. Fission occurs with high probability in the fissile nuclides: uranium-233, uranium-235, plutonium-239, and plutonium-241. Of these only U-235 occurs in nature, at about 0.72 per cent of natural uranium. The others are produced artificially by neutron capture followed by radioactive decay." },
  { t: "p", x: "Only three nuclides are simultaneously stable enough to store, available in practice, and capable of fissioning across the whole neutron energy range from thermal, at 0.025 electron-volts or less, up to millions of electron-volts: U-233, U-235, and Pu-239. The program offers three more — Pu-241, Am-242, and Cm-245 — not because you could build with them, but because including them sharpens the comparison. Americium-242 has a thermal fission cross section of 6000 barns against uranium-235's 582, and seeing what that does to the critical mass teaches something that no amount of reading will." },
  { t: "p", x: "The energy released per fission is distributed among the kinetic energy of the fragments, which is deposited locally in the fuel and is the source of essentially all the useful heat; the kinetic energy of the neutrons; prompt gamma rays; and the delayed beta and gamma emissions of the fission products. It is the last of these that produces decay heat after shutdown, and that makes a reactor a system you cannot simply switch off." },

  { t: "h2", x: "2.2 Prompt and delayed neutrons" },
  { t: "p", x: "Most neutrons appear essentially instantly, about 10⁻⁴ seconds after the fission. These are prompt neutrons. A small fraction — 0.65 per cent for U-235 — are emitted between 0.2 and 55 seconds after the fission, as certain fission products beta-decay into excited states that promptly shed a neutron. These are the delayed neutrons, and the entire practice of reactor control rests on them." },
  { t: "p", x: "The reason is arithmetic. If all neutrons were prompt, the mean generation time would be about 10⁻⁴ seconds, and a reactivity insertion of 0.003 would multiply the power by a factor of roughly 8000 in a third of a second. No operator and no mechanical control system could respond to that. The delayed fraction stretches the effective mean generation time by three orders of magnitude, into the range of seconds, which brings reactor power into the domain of human and machine control. A reactor that is critical on prompt neutrons alone — prompt critical — is out of control by definition." },

  { t: "h2", x: "2.3 The neutron life cycle" },
  { t: "p", x: "Follow one generation of neutrons around the cycle. Fast neutrons born in fission may cause further fast fissions, which multiplies their number slightly; this is the fast fission factor ε. Some fast neutrons leak out of the core and are lost, a loss described by the fast non-leakage probability. The survivors slow down through elastic collisions with moderator nuclei; some are captured in the resonance region on the way down, and the fraction that escapes this is the resonance escape probability p. Of the neutrons that reach thermal energy, some are absorbed in the moderator, coolant, or structure rather than in the fuel; the fraction absorbed in fuel is the thermal utilisation f. More thermal neutrons leak out, described by the thermal non-leakage probability. Finally, each thermal neutron absorbed in fuel produces η new fast neutrons on average, and the cycle repeats." },
  { t: "fig", src: "fig1-lifecycle.png", w: 624, h: 248, n: 1, cap: "The neutron life cycle. The effective multiplication factor is the product of the four factors and the two non-leakage probabilities. The program solves for the composition that makes this product equal to one." },
  { t: "p", x: "The effective multiplication factor is the product of all six terms. When it equals one, the neutron population is steady and the reactor is CRITICAL. When it exceeds one, the population grows and the reactor is SUPERCRITICAL. When it falls below one, the population declines and the reactor is SUBCRITICAL. These are statements about the rate of change of the neutron population, not about power level: a reactor can be critical at one watt or at three thousand megawatts." },
  { t: "p", x: "The two leakage terms are where geometry enters. Both depend on the geometric buckling B², a purely dimensional quantity that measures how sharply the neutron flux must curve to fall to zero at the core boundary. A small core has a large buckling and leaks heavily. A large core has a small buckling and leaks little. This is the single most important structural fact in the whole calculation, and Chapter 4 develops it." },

  { t: "h2", x: "2.4 Reactivity" },
  { t: "p", x: "Reactivity measures how far a reactor is from critical. It is defined as ρ = 1 − 1/k_eff, so that a critical reactor has zero reactivity. Reactivity is inserted into or removed from a core by five mechanisms, and their sum is the net reactivity at any moment." },
  { t: "numbers", x: [
    "Coolant temperature. A change in the average coolant temperature changes the moderator density, which changes the rate at which neutrons slow down and therefore the neutron population. Temperature also changes Doppler broadening, the widening of the resonance absorption peaks in the fuel as thermal motion increases. The combination is the temperature coefficient. Every power reactor is required to have a negative temperature coefficient, so that a rise in temperature inserts negative reactivity and the reactor is self-regulating.",
    "Pressure. Higher pressure raises moderator density and therefore reactivity. The effect is small in a liquid-cooled reactor and is usually neglected.",
    "Control rod position. Rods are strong neutron absorbers. Moving them into the flux inserts negative reactivity; withdrawing them inserts positive reactivity. Differential rod worth is the reactivity change per unit of rod travel, and it varies along the rod because the flux varies along the core.",
    "Fuel depletion and burnable poison depletion. Fuel is consumed as the core runs, which removes reactivity. Burnable poisons are deliberately placed absorbers that burn out on a matched schedule, holding the net change small and extending core life.",
    "Fission product poisoning. Some fission products, xenon-135 above all, are extremely strong thermal absorbers. Xenon builds up after a power reduction and then decays, producing the characteristic dead time after a shutdown during which the reactor cannot be restarted.",
  ]},
  { t: "p", x: "At every point in core life the design must be able to go critical, to shut down, and to be controlled across the full range of possible conditions, with a defined margin. That requirement is what sets the initial fuel enrichment: the cold, clean core must carry enough excess reactivity to cover heating to operating temperature, the Doppler effect, burnup over the whole cycle, fission product poisoning, control rod absorption, and burnable poison loading." },

  // ------------------------------------------------------------------ Ch 3
  { t: "h1", x: "3. Moderation, Diffusion, and the Fermi Age" },

  { t: "h2", x: "3.1 Why slow neutrons" },
  { t: "p", x: "A thermal neutron is far more likely to cause fission in U-235 than a fast one — the thermal fission cross section is 582 barns against a fraction of a barn at fission energies. To minimise the critical mass, you therefore want most fissions to be caused by thermal neutrons. That means distributing the fuel inside a moderating material whose job is to slow the fast neutrons down through elastic scattering, without absorbing them along the way." },
  { t: "p", x: "A good moderator has three properties: a low mass number, so each collision removes a large fraction of the neutron's energy; a high scattering cross section, so collisions are frequent; and a low absorption cross section, so few neutrons are lost in the process. Ordinary water, heavy water, beryllium, and carbon are the classical choices, and all five moderators offered by the program are drawn from that set." },
  { t: "p", x: "Ordinary water is the best slowing-down agent by a wide margin — hydrogen has almost the same mass as a neutron, so a single head-on collision can stop it dead — but hydrogen also absorbs neutrons, with a cross section of 0.66 barns per water molecule. Heavy water absorbs 330 times less, at 0.002 barns, but slows neutrons less efficiently. That single trade-off explains why light-water reactors need enriched uranium and heavy-water reactors like CANDU can run on natural uranium." },

  { t: "h2", x: "3.2 The Fermi age" },
  { t: "p", x: "The Fermi age τ is not a time. It is an area, measured in cm², and it equals one sixth of the mean square distance a neutron travels in a straight line from its birth as a fast neutron to the moment it reaches thermal energy. It is the natural measure of how far neutrons wander while slowing down." },
  { t: "p", x: "Fermi age matters because it controls fast leakage. In the age approximation, the probability that a fast neutron survives slowing down without escaping the core is exp(−B²τ). A moderator with a small age keeps the slowing-down process compact, so even a small core can hold onto its fast neutrons. Water's age is 31.4 cm²; graphite's is 350 cm², more than eleven times larger. That is why a graphite-moderated reactor must be physically large: the neutrons simply travel too far while slowing down for a small core to contain them." },

  { t: "h2", x: "3.3 The diffusion length" },
  { t: "p", x: "Once a neutron reaches thermal energy it wanders as a thermal neutron until it is absorbed. The diffusion length squared, L², measures that wandering the same way the age measures the slowing-down phase. In the one-group treatment, the thermal non-leakage probability is 1/(1 + L²B²)." },
  { t: "p", x: "L² varies enormously across moderators — from 7.6 cm² for water to 10,000 cm² for heavy water — and the reason is absorption. A thermal neutron in heavy water is almost never absorbed, so it diffuses a very long way before it finds something to react with. That is excellent for neutron economy and poor for compactness. Table II in Appendix A lists both τ and L² for all five moderators, and comparing the two columns is the fastest way to understand why the five behave so differently." },

  { t: "h2", x: "3.4 The moderator-to-fuel ratio" },
  { t: "p", x: "The relative amounts of moderator and fuel are expressed as the moderator-to-fuel ratio, the number of moderator atoms per fuel atom. This is the quantity the program actually solves for. Everything else about criticality follows from it." },
  { t: "p", x: "The ratio has an optimum, and the reason is a competition. Too little moderator, and neutrons are not slowed enough; they are lost to resonance capture and to fast leakage before they can cause thermal fission. This is an under-moderated core. Too much moderator, and the moderator itself starts absorbing a significant share of the thermal neutrons, while the fuel becomes so dilute that thermal utilisation collapses. This is an over-moderated core. Power reactors are deliberately built under-moderated, because in that condition a rise in temperature — which expels moderator and reduces the ratio — reduces reactivity, giving the negative temperature coefficient that safety requires." },
  { t: "p", x: "When the program reports a moderator-to-fuel ratio of 883 for the default case, it is telling you that criticality requires 883 water molecules for every uranium-235 atom. When it reports a negative ratio, it is telling you that no ratio exists that will work: leakage and parasitic absorption exceed what the fuel can supply, and the geometry must change." },

  // ------------------------------------------------------------------ Ch 4
  { t: "h1", x: "4. Geometry, Buckling, and Critical Size" },

  { t: "h2", x: "4.1 The one-group criticality condition" },
  { t: "p", x: "Combining the age treatment of slowing down with one-group diffusion theory for thermal neutrons gives a criticality condition that can be written, for a bare homogeneous reactor, as" },
  { t: "eq", x: "η · exp(−B²τ) / (1 + L²B²) = 1" },
  { t: "p", x: "where η is the number of fission neutrons produced per thermal neutron absorbed in fuel, τ is the Fermi age of the moderator, L² is the thermal diffusion length squared, and B² is the geometric buckling. The numerator is production discounted by fast leakage; the denominator is the thermal leakage penalty. The program rearranges this expression to solve for the moderator-to-fuel ratio, treating the absorption in fuel, moderator, and coolant explicitly. It holds η at 2.06, the U-235 value, for every fuel — one of the approximations you should keep in mind when comparing fuels." },

  { t: "h2", x: "4.2 Buckling and the three core shapes" },
  { t: "p", x: "Geometric buckling is a property of the shape and size alone. It is the eigenvalue of the flux shape that vanishes at the extrapolated boundary, and it has units of cm⁻². Physically it is a measure of curvature: the more sharply the flux must bend to reach zero at the surface, the larger the buckling, and the more neutrons escape." },
  { t: "fig", src: "fig2-geometry.png", w: 624, h: 235, n: 2, cap: "Geometric buckling for the three core shapes offered by the program, with the corresponding minimum critical volumes. Dimensions are entered in centimetres." },
  { t: "p", x: "For a rectangular parallelepiped with edges a, b, and c, the buckling is the sum of three squared terms, (π/a)² + (π/b)² + (π/c)². For a cylinder of radius R and height H it is (2.405/R)² + (π/H)², where 2.405 is the first zero of the Bessel function J₀ that describes the radial flux shape. For a sphere of radius R it is simply (π/R)²." },
  { t: "p", x: "Because buckling is a sum of inverse-square dimensions, doubling every dimension divides the buckling by four. Small cores leak catastrophically; large cores barely leak at all. The consequence is visible in every result the program produces." },

  { t: "h2", x: "4.3 Why the sphere is optimal" },
  { t: "p", x: "For a given material composition, the critical volume — and therefore the critical mass — is smallest for a sphere. The reason is geometric rather than nuclear. Neutron production happens throughout the volume, but neutron leakage happens only at the surface. The sphere has the smallest surface-to-volume ratio of any shape, so it loses the least." },
  { t: "p", x: "The classical minimum critical volumes reflect this ordering directly: (130/B)³ for a sphere, (161/B)³ for a cylinder at its optimum proportion of H = 1.847R, and (148/B)³ for a cube. You can verify the ordering in the program. Setting three cores of equal 8 m³ volume in the three shapes, with U-235 in light water, gives the following." },
  { t: "table", head: ["Shape", "Dimensions (cm)", "B² (cm⁻²)", "Nm/Nf", "Critical mass (kg)"], rows: [
    ["Cube", "200 × 200 × 200", "7.402 × 10⁻⁴", "1036.0", "100.81"],
    ["Cylinder, H = 1.847R", "R 111.3, H 205.6", "7.005 × 10⁻⁴", "1038.9", "100.53"],
    ["Sphere", "R 124.1", "6.411 × 10⁻⁴", "1043.2", "100.12"],
  ], widths: [1900, 2200, 1900, 1600, 1760], n: 1, cap: "Three cores of equal volume. The sphere has the lowest buckling and the lowest critical mass, as theory requires. The differences are small at this size because leakage is already low." },
  { t: "p", x: "The differences are under one per cent here, because an 8 m³ core is large enough that leakage is a minor term. Repeat the comparison at 0.1 m³ and the sphere's advantage becomes dramatic. That is itself a useful lesson: geometry matters most when you are close to the margin." },

  { t: "h2", x: "4.4 Critical mass and core size" },
  { t: "p", x: "The relationship between core size and critical mass is not monotonic, and this surprises most students. Figure 3 plots it for U-235 in light water across the full range the program accepts." },
  { t: "fig", src: "fig6-critmass.png", w: 624, h: 247, n: 3, cap: "Critical mass against cube edge length for U-235 in light water. Panel (a) resolves the region near the critical threshold; panel (b) shows the full design range. Note the logarithmic vertical scale." },
  { t: "p", x: "Three regions appear. Below about a 35 cm cube, no moderator-to-fuel ratio achieves criticality at all: leakage dominates completely, and the program refuses the design. Just above that threshold the critical mass falls steeply, from 110 kg at 36 cm to 9.7 kg at 38 cm, as the leakage penalty relaxes. The curve reaches a minimum of 4.09 kg at a cube of about 48 cm edge, roughly 0.11 m³. Beyond that, critical mass rises steadily with volume, reaching 331 kg at 300 cm and 1509 kg at 500 cm." },
  { t: "p", x: "The minimum exists because two effects run against each other. As the core grows, the required fuel concentration falls — leakage is less punishing, so a more dilute mixture will do. But the volume grows as the cube of the dimension. Below the minimum the concentration term wins; above it the volume term wins. Real power reactors sit far to the right of the minimum, because they are sized for power output and heat removal, not for minimum fuel inventory." },
];
