// Appendices.

export const appendices = [
  { t: "h1", x: "Appendix A: Data Tables" },
  { t: "p", x: "These are the values the program uses. They are carried over unchanged from the 1993 source and are typical thermal-spectrum figures; consult a current evaluated nuclear data library for design work." },

  { t: "h2", x: "Table I. Reactor fuels" },
  { t: "table", head: ["Isotope", "Density (g/cc)", "Mass number", "σ fission (barns)", "σ absorption (barns)", "k (BTU/hr·ft·°F)"], rows: [
    ["U-233", "19.0", "233", "514", "569", "14"],
    ["U-235", "19.0", "235", "582", "679", "14"],
    ["Pu-239", "19.0", "239", "760", "1030", "14"],
    ["Pu-241", "19.0", "241", "988", "1384", "14"],
    ["Am-242", "19.0", "242", "6000", "7700", "14"],
    ["Cm-245", "19.0", "245", "1700", "2000", "14"],
  ], widths: [1500, 1700, 1500, 1600, 1800, 1260] },
  { t: "note", x: "Cross sections are thermal values at 0.025 eV. All six fuels share a density of 19.0 g/cc and a thermal conductivity of 14 BTU/hr·ft·°F in the program; real values differ, particularly for oxide fuels, whose conductivity is roughly an order of magnitude lower." },

  { t: "h2", x: "Table II. Reactor moderators" },
  { t: "table", head: ["Material", "L² (cm²)", "Fermi age τ (cm²)", "Density (g/cc)", "σ absorption (barns)", "Mass number"], rows: [
    ["Light water, H₂O", "7.617", "31.36", "1.00", "0.66", "18"],
    ["Heavy water, D₂O", "10,000", "121", "1.10", "0.002", "20"],
    ["Beryllium, Be", "441", "84.64", "1.85", "0.01", "9"],
    ["Carbon-12", "4121", "350", "1.90", "0.004", "12"],
    ["Carbon-13", "4121", "350", "1.90", "0.002", "13"],
  ], widths: [2100, 1500, 1900, 1700, 1800, 1360] },
  { t: "note", x: "The two length scales tell the story: Fermi age governs how far neutrons travel while slowing down, and L² governs how far they travel afterwards. Light water is compact in both; the graphites are extended in both." },

  { t: "h2", x: "Table III. Reactor coolants" },
  { t: "table", head: ["Coolant", "Heat capacity (BTU/lb·°F)", "Density range (g/cc)", "σ absorption (barns)", "Loop"], rows: [
    ["Water, H₂O", "1.00 to 1.37", "0.67 to 1.00", "0.66", "Closed"],
    ["Hydrogen, H₂", "2.59 to 3.74", "0.000019 to 0.00083", "0.33", "Open"],
    ["Helium, He", "1.242 (constant)", "0.000053 to 0.0034", "0.007", "Closed"],
    ["Sodium, Na", "0.300 to 0.331", "0.72 to 0.93", "0.525", "Closed"],
  ], widths: [1900, 2500, 2300, 1900, 1160] },
  { t: "note", x: "Properties are looked up from step tables keyed on the minimum coolant temperature. Selecting hydrogen forces an open loop; the other three use a closed loop with water as the secondary fluid. Hydrogen and helium are additionally limited to Mach 0.3." },

  { t: "h2", x: "Table IV. Default values" },
  { t: "table", head: ["Parameter", "Default"], rows: [
    ["Fuel", "Uranium-235"],
    ["Moderator", "Light water"],
    ["Primary coolant", "Water"],
    ["Secondary coolant", "Water"],
    ["Geometry", "Rectangular, 100 × 100 × 100 cm"],
    ["Maximum coolant temperature", "530 K"],
    ["Minimum coolant temperature", "470 K"],
    ["Coolant tube diameter", "0.4 cm"],
    ["Porosity", "0.33"],
    ["Coolant flowrate", "10,000 kg/s"],
    ["Power conversion", "Closed loop"],
    ["Resulting coolant pressure", "92 atmospheres"],
  ], widths: [4800, 4560] },

  { t: "h2", x: "Table V. Secondary loop state points" },
  { t: "table", head: ["Point", "Location", "Temperature", "Pressure (atm)", "Enthalpy (BTU/lb)"], rows: [
    ["4", "Steam generator outlet", "516 K", "34.9", "1205"],
    ["5", "Turbine exhaust", "52", "0.1436", "850"],
    ["6", "Condenser hotwell", "41", "0.0769", "68"],
    ["7", "Feedwater to steam generator", "104", "34.9", "168"],
  ], widths: [1100, 3400, 1700, 1700, 1460] },
  { t: "note", x: "These four points are fixed and do not vary with your design. The temperatures at points 5, 6, and 7 are labelled as kelvin in the original program, but 41 K is physically impossible for a condenser and the values are consistent with degrees Celsius: 52 °C turbine exhaust, 41 °C condenser, 104 °C feedwater. Read them as Celsius. The enthalpies are self-consistent and produce a cycle efficiency of 34.2 per cent, which is correct for a plant of this type." },

  { t: "h1", x: "Appendix B: Assumptions and Limitations" },
  { t: "p", x: "Every result the program produces rests on the following. Reading this list is the difference between using the program well and being misled by it." },
  { t: "numbers", x: [
    "Criticality is computed using the thermal group approximation, the homogeneous reactor approximation, and the Fermi age approximation. These are the standard hand-calculation methods of the 1950s and 1960s. They capture the correct sensitivities but not the correct absolute values for a heterogeneous lattice.",
    "The core is bare: no reflector is modelled. A real reflected core reaches criticality with substantially less fuel, often a third less, so every critical mass reported here is conservative in that respect.",
    "Fuel and moderator are treated as uniformly mixed. Real cores arrange fuel in pins within a moderator lattice, which changes resonance escape and thermal utilisation appreciably.",
    "The neutron reproduction factor η is held at 2.06, the U-235 value, for every fuel. Comparisons between fuels therefore show the effect of cross sections only, not the full picture.",
    "Critical mass is given for the pure isotope. Use Define Your Own Fuel to model alloys, oxides, and realistic enrichments.",
    "Annual burnup assumes continuous operation at 100 per cent power with zero breeding.",
    "Secondary loop state points are fixed. Cycle efficiency is therefore constant at 34.2 per cent for closed loops regardless of primary conditions, and the efficiency gain that a higher primary temperature would deliver in reality is not shown.",
    "Open loop conversion is a flat 36 per cent.",
    "Gas coolants are limited to Mach 0.3, computed at the maximum coolant temperature. When the limit binds, velocity is clipped and system pressure is raised.",
    "Pressure drop uses the Blasius correlation for smooth turbulent pipe flow with a 1.5 multiplier for form losses. It assumes incompressible flow and neglects elevation and acceleration terms.",
    "No burnup over time, fission product poisoning, control rod worth, transient behaviour, shielding thickness, structural analysis, or cost estimation is performed.",
    "Four leftover debugging statements in the 1993 source, which pinned primary pressure, pump power, and turbine output to constants and which corrupted coolant velocity through a misplaced conditional, have been corrected in the browser edition. All physics, material data, and correlations are otherwise unchanged.",
  ]},

  { t: "h1", x: "Appendix C: Reference Plants" },
  { t: "p", x: "Two operating plants, for comparison against your designs. The Summary output page shows these alongside your current case." },
  { t: "table", head: ["Quantity", "Oconee 1 (PWR)", "Pickering (HWR)", "Units"], rows: [
    ["Thermal power", "2584", "1742", "MWth"],
    ["Electrical power", "886", "508", "MWe"],
    ["Core volume", "30.7", "265", "m³"],
    ["Fuel form", "UO₂", "UO₂", "—"],
    ["Fuel mass", "83,000", "92,600", "kg"],
    ["Coolant temperature", "563 to 591", "523 to 567", "K"],
    ["Coolant flowrate", "12,600", "17,700", "kg/s"],
    ["Power density", "31.1", "10", "W/g"],
    ["Average heat flux", "54.1", "59.2", "W/cm²"],
    ["Net efficiency", "34.3", "29.2", "per cent"],
  ], widths: [2900, 2200, 2200, 2060] },

  { t: "h1", x: "Appendix D: Equation Summary" },
  { t: "p", x: "The equations the program evaluates, in the order it evaluates them." },
  { t: "eqlist", x: [
    ["Geometric buckling, rectangular", "B² = (π/a)² + (π/b)² + (π/c)²"],
    ["Geometric buckling, cylindrical", "B² = (2.405/R)² + (π/H)²"],
    ["Geometric buckling, spherical", "B² = (π/R)²"],
    ["Coolant channel count", "N = εV / (πd²/4 · L)"],
    ["Coolant velocity", "v = ṁ / (ρ · N · πd²/4)"],
    ["Reynolds number", "Re = v · ρ · d / μ"],
    ["Friction factor (Blasius)", "f = 0.079 · Re⁻⁰·²⁵"],
    ["Core pressure drop", "Δp = 1.5 · 4f · (L/d) · ρv² / (2g)"],
    ["Thermal power", "P = ṁ · cp · (Tmax − Tmin)"],
    ["Power density", "q = P / [V(1 − ε)]"],
    ["Average heat flux", "q\" = P / (π d L N)"],
    ["Fuel centreline temperature", "Tc = Tmax + 200 + q · rf² / (4 · 1.73 · k)"],
    ["Criticality condition", "η · exp(−B²τ) / (1 + L²B²) = 1"],
    ["Moderator-to-fuel ratio", "Nm/Nf = [η·exp(−B²τ) − 1]·σaf / [(1 + L²B²)·σ̄a]"],
    ["Moderator number density", "Nm = ρm · NA / Am"],
    ["Critical mass", "M = V · (Af/Am) · ρm / (Nm/Nf) · 1000"],
    ["Specific power", "S = P / M"],
    ["Thermal neutron flux", "φ = 3.1 × 10¹⁰ · P / (V · Nf · σf · 10⁻²⁴)"],
    ["Secondary flowrate", "ṁ₂ = 1000 P / (h₄ − h₇)"],
    ["Turbine power", "W = ṁ₂ · (h₄ − h₅)"],
    ["Cycle efficiency", "ηcycle = 100 · W / P"],
  ]},
  { t: "note", x: "Symbols: a, b, c are rectangular edge lengths; R and H are cylinder radius and height; ε is porosity; V is core volume; d is tube diameter; L is channel length; ṁ is coolant mass flow; ρ is coolant density; μ is viscosity; cp is specific heat; τ is Fermi age; L² is diffusion length squared; σaf is the fuel absorption cross section; σ̄a is the mass-weighted moderator and coolant absorption cross section; Af and Am are fuel and moderator mass numbers; ρm is moderator density; NA is Avogadro's number; h are secondary enthalpies." },

  { t: "h1", x: "Appendix E: Worked Example Results" },
  { t: "p", x: "All four worked examples side by side. Every figure was produced by the program at the settings given in the corresponding chapter." },
  { t: "table", head: ["Quantity", "Ex 1 PWR", "Ex 2 HWR", "Ex 3 HTGR", "Ex 4 NTP"], rows: [
    ["Fuel", "U-235", "U-235", "U-235", "U-235"],
    ["Moderator", "H₂O", "D₂O", "C-12", "Be"],
    ["Coolant", "H₂O", "H₂O", "He", "H₂"],
    ["Geometry", "cube 300", "cyl 200/370", "sphere 250", "cyl 40/90"],
    ["Core volume, m³", "27.0", "46.5", "65.4", "0.452"],
    ["Buckling, cm⁻²", "3.29 × 10⁻⁴", "2.17 × 10⁻⁴", "1.58 × 10⁻⁴", "4.83 × 10⁻³"],
    ["Nm/Nf", "1066", "1010", "97,600", "7970"],
    ["Critical mass, kg", "331", "596", "24.9", "2.74"],
    ["Thermal power, MWth", "3950", "3230", "6230", "1200"],
    ["Electrical power, MWe", "1353", "1113", "2131", "432"],
    ["Power density, MW/m³", "218", "116", "136", "5310"],
    ["Heat flux, W/cm²", "44.3", "17.4", "95.2", "796"],
    ["Coolant velocity, m/s", "5.83", "4.31", "438", "1250"],
    ["Pump power, MWe", "3.40", "2.57", "145", "73.1"],
    ["Fuel temperature, K", "766", "789", "1300", "4570"],
    ["Efficiency, per cent", "34.2", "34.2", "34.2", "36.0"],
  ], widths: [2600, 1700, 1700, 1700, 1660] },
  { t: "note", x: "Example 1 is the uprated case of Section 9.3. Examples 3 and 4 are Mach limited. Example 4's fuel temperature exceeds the melting point of every known fuel form and the design is not feasible as entered; Chapter 12 discusses the remedies." },

  { t: "h1", x: "Appendix F: Online Resources" },
  { t: "p", x: "The program and its sources are freely available." },
  { t: "linklist", x: [
    ["Run the program", "https://reactor-seven.vercel.app/", "The browser edition. Nothing to install; all computation happens locally in your browser."],
    ["Project repository", "https://github.com/alessoh/reactor", "The 1993 Visual Basic sources, the original user's manual and tutorial, the installation disk images, and the browser reconstruction."],
    ["Tutorial, in-program", "https://reactor-seven.vercel.app/", "Help then Tutorial. Seven sections covering the physics, geometry, heat removal, control, and background."],
    ["Data tables, in-program", "https://reactor-seven.vercel.app/", "Tools then Appendix A. The same fuel, moderator, and coolant data reproduced in this appendix."],
    ["USNRC Glossary", "https://www.nrc.gov/reading-rm/basic-ref/glossary.html", "Authoritative definitions of regulatory and technical terms."],
    ["IAEA Power Reactor Information System", "https://pris.iaea.org/", "Operating data for every power reactor in the world; useful for benchmarking your designs."],
  ]},
  { t: "p", x: "To reproduce any table in this manual, open the program, enter the settings given in the corresponding chapter, and read the output pages. Every figure quoted here came from the program itself." },
];
