// Worked examples, parametric studies, troubleshooting.

export const examples = [
  // ------------------------------------------------------------------ Ch 9
  { t: "h1", x: "9. Worked Example 1: A Pressurised Water Reactor" },
  { t: "p", x: "This example takes the demonstration default, shows that it is thermally impossible, and repairs it. It is the most instructive exercise in the manual because the repair is driven entirely by numbers the program reports." },

  { t: "h2", x: "9.1 Run the default and read the warning signs" },
  { t: "steps", x: [
    "Open https://reactor-seven.vercel.app/ and, if you have been experimenting, choose Files then Reset to defaults.",
    "Confirm the settings: U-235 fuel, light water moderator, water coolant, rectangular geometry at 100 × 100 × 100 cm, 530 K maximum and 470 K minimum coolant temperature, 0.4 cm tubes, 0.33 porosity, 10,000 kg/s flow.",
    "Read the Reactor output page.",
  ]},
  { t: "table", head: ["Quantity", "Value", "Comment"], rows: [
    ["Core volume", "1.00 m³", "Very small for a power reactor"],
    ["Geometric buckling", "2.96 × 10⁻³ cm⁻²", "High — significant leakage"],
    ["Moderator-to-fuel ratio", "883", "Criticality is achieved"],
    ["Critical mass", "14.8 kg U-235", "Plausible for this size"],
    ["Thermal power", "2633 MWth", "Comparable to Oconee 1"],
    ["Power density", "3930 MW/m³", "About 125 times operating practice"],
    ["Average heat flux", "798 W/cm²", "About 15 times operating practice"],
    ["Maximum fuel temperature", "1380 K", "Below the UO₂ melting point"],
    ["Electrical power", "902 MWe", "34.2 per cent cycle efficiency"],
  ], widths: [3100, 2300, 3960], n: 2, cap: "Demonstration default, Reactor page. The power and efficiency are realistic; the power density and heat flux are not." },
  { t: "p", x: "The design is critical and it produces a believable 2633 MWth and 902 MWe — figures very close to Oconee 1's 2584 MWth and 886 MWe, which the Summary page shows for comparison. But the power density and heat flux are absurd. Oconee runs at about 31 W/g and 54 W/cm². This design demands 798 W/cm²." },
  { t: "p", x: "Now open the Primary page." },
  { t: "table", head: ["Quantity", "Value", "Operating practice"], rows: [
    ["Coolant velocity", "35.0 m/s", "4 to 6 m/s"],
    ["Reynolds number", "1.18 × 10⁶", "Turbulent, as expected"],
    ["Core pressure drop", "18.8 atm", "1 to 3 atm"],
    ["Primary pump power", "17.4 MWe", "Under 1 per cent of gross output"],
    ["Number of channels", "26,300", "—"],
  ], widths: [3100, 2300, 3960], n: 3, cap: "Demonstration default, Primary page. Every hydraulic quantity is far outside operating practice." },
  { t: "p", x: "The diagnosis is now unambiguous. The core is being asked to pass the coolant flow of a full-size power plant through one cubic metre. The heat is generated in the right total amount, but there is nowhere near enough surface area to transfer it, and nowhere near enough flow area to carry it. The fix is not to reduce the power. It is to make the core the right size." },

  { t: "h2", x: "9.2 Enlarge the core" },
  { t: "p", x: "Oconee 1 has a core volume of 30.7 m³. A cube of 300 cm on each side gives 27 m³, which is close enough to compare directly." },
  { t: "steps", x: [
    "In the Geometry section, set Length x, Length y, and Length z each to 300 cm.",
    "Leave everything else unchanged.",
    "Read the Reactor and Primary pages again.",
  ]},
  { t: "table", head: ["Quantity", "1 m core", "27 m³ core", "Oconee 1"], rows: [
    ["Core volume, m³", "1.00", "27.0", "30.7"],
    ["Buckling, cm⁻²", "2.96 × 10⁻³", "3.29 × 10⁻⁴", "—"],
    ["Moderator-to-fuel ratio", "883", "1066", "—"],
    ["Critical mass, kg U-235", "14.8", "331", "—"],
    ["Thermal power, MWth", "2633", "2633", "2584"],
    ["Electrical power, MWe", "902", "902", "886"],
    ["Power density, MW/m³", "3930", "146", "—"],
    ["Heat flux, W/cm²", "798", "29.6", "54.1"],
    ["Fuel temperature, K", "1380", "754", "—"],
    ["Coolant velocity, m/s", "35.0", "3.89", "—"],
    ["Pressure drop, atm", "18.8", "1.21", "—"],
    ["Pump power, MWe", "17.4", "1.12", "—"],
    ["Coolant channels", "26,300", "236,000", "—"],
  ], widths: [3000, 2100, 2100, 2160], n: 4, cap: "The effect of enlarging the core twenty-sevenfold at constant flow conditions. Power and efficiency are unchanged; every thermal and hydraulic quantity moves into operating range." },
  { t: "p", x: "Every problem is solved at once, and it is worth being precise about why. The thermal power did not change, because it is set by the coolant energy balance and the flow conditions were not touched. What changed is that the same power is now generated in twenty-seven times the volume, spread over nine times the channel wall area, and carried by coolant through nine times the flow area. Power density falls by a factor of twenty-seven, heat flux by a factor of nine, velocity by a factor of nine, and pressure drop and pumping power by more than that because they scale with higher powers of velocity." },
  { t: "p", x: "The cost is fuel. The critical mass rises from 14.8 kg to 331 kg, a factor of twenty-two, because a larger core leaks proportionally less and therefore needs a more dilute — but far more voluminous — fuel loading. This is the central trade of thermal reactor design stated in two numbers: you buy thermal feasibility with fuel inventory." },
  { t: "p", x: "The heat flux at 29.6 W/cm² is now conservative against Oconee's 54.1, which suggests headroom. Confirm it by raising the flow." },

  { t: "h2", x: "9.3 Uprate the design" },
  { t: "steps", x: [
    "Set Coolant flowrate to 15,000 kg/s.",
    "Leave the geometry at 300 cm and the temperatures unchanged.",
  ]},
  { t: "table", head: ["Quantity", "10,000 kg/s", "15,000 kg/s"], rows: [
    ["Thermal power, MWth", "2633", "3950"],
    ["Electrical power, MWe", "902", "1353"],
    ["Power density, MW/m³", "146", "218"],
    ["Heat flux, W/cm²", "29.6", "44.3"],
    ["Fuel temperature, K", "754", "766"],
    ["Coolant velocity, m/s", "3.89", "5.83"],
    ["Pressure drop, atm", "1.21", "2.45"],
    ["Pump power, MWe", "1.12", "3.40"],
    ["Secondary flowrate, kg/s", "1100", "1660"],
  ], widths: [3400, 2500, 2460], n: 5, cap: "Uprating by 50 per cent flow. Output rises proportionally; heat flux and velocity remain within operating practice." },
  { t: "p", x: "A 50 per cent increase in flow buys a 50 per cent increase in output, to 3950 MWth and 1353 MWe, while the heat flux reaches only 44.3 W/cm² and the velocity 5.83 m/s — both still inside operating experience. Pumping power triples to 3.40 MWe, which is the price, but it is a quarter of one per cent of gross output. The fuel centreline temperature barely moves, rising from 754 K to 766 K, because it is dominated by the fixed coolant temperature and the film allowance rather than by the conduction term at these power densities." },
  { t: "p", x: "This is a credible large PWR. Save it: click Save case, and it appears in the comparison table for later reference." },

  // ------------------------------------------------------------------ Ch 10
  { t: "h1", x: "10. Worked Example 2: A Heavy-Water Reactor" },
  { t: "p", x: "Heavy water absorbs 330 times fewer thermal neutrons than light water. The consequence is that a heavy-water reactor can achieve criticality with natural or very slightly enriched uranium — the basis of the Canadian CANDU design. The cost is size, because heavy water's Fermi age of 121 cm² and diffusion length squared of 10,000 cm² both far exceed light water's." },
  { t: "steps", x: [
    "Set the moderator to D2O.",
    "Set the geometry to Cylindrical, with radius 200 cm and height 370 cm.",
    "Set maximum coolant temperature 570 K, minimum 530 K.",
    "Set porosity 0.40 and coolant flowrate 17,000 kg/s. Leave tube diameter at 0.4 cm.",
  ]},
  { t: "table", head: ["Quantity", "Value", "Pickering (HWR)"], rows: [
    ["Core volume", "46.5 m³", "265 m³"],
    ["Geometric buckling", "2.17 × 10⁻⁴ cm⁻²", "—"],
    ["Moderator-to-fuel ratio", "1010", "—"],
    ["Critical mass", "596 kg U-235", "—"],
    ["Moderator mass", "30.7 Mg D₂O", "—"],
    ["Thermal power", "3230 MWth", "1742 MWth"],
    ["Electrical power", "1113 MWe", "508 MWe"],
    ["Power density", "116 MW/m³", "—"],
    ["Heat flux", "17.4 W/cm²", "59.2 W/cm²"],
    ["Coolant velocity", "4.31 m/s", "—"],
    ["Primary pressure", "124 atm", "—"],
    ["Fuel temperature", "789 K", "—"],
  ], widths: [3300, 2600, 2460], n: 6, cap: "Heavy-water cylindrical core. Note the low heat flux and the high primary pressure demanded by the 530 to 570 K operating range." },
  { t: "p", x: "Two features distinguish this case from the PWR. First, the critical mass of 596 kg is well above the light-water design's 331 kg despite a comparable buckling, because heavy water's long diffusion length means thermal neutrons wander a long way and a larger fuel inventory is needed to catch them. Compare the two moderators directly in Chapter 13 and the pattern is clearer." },
  { t: "p", x: "Second, the primary pressure of 124 atm is a direct consequence of the operating temperature. The program looks up the saturation pressure of water at the minimum coolant temperature and applies a safety factor of two. Running at 530 K requires the primary circuit to be pressurised well above saturation to prevent bulk boiling, and that pressure sets the vessel wall thickness — and much of the cost. Lower the minimum temperature to 470 K and watch the required pressure fall by more than half." },
  { t: "p", x: "The heat flux of 17.4 W/cm² is very conservative, which reflects the enormous channel surface area created by a 0.4 cm tube in a 46.5 m³ core at 40 per cent porosity — roughly 400,000 channels. A real CANDU uses far fewer, much larger pressure tubes." },

  // ------------------------------------------------------------------ Ch 11
  { t: "h1", x: "11. Worked Example 3: A High-Temperature Gas Reactor" },
  { t: "p", x: "Graphite moderation with helium cooling permits outlet temperatures far above what water allows, because helium does not boil, does not corrode, and absorbs almost no neutrons. The penalty is a very large core — graphite's Fermi age of 350 cm² is eleven times water's — and the difficulty of pumping a gas." },
  { t: "steps", x: [
    "Set the fuel to U-235 and the moderator to C-12.",
    "Set the coolant to He.",
    "Set the geometry to Spherical with radius 250 cm.",
    "Set maximum coolant temperature 1000 K, minimum 600 K.",
    "Set tube diameter 1.2 cm, porosity 0.30, flowrate 3000 kg/s.",
  ]},
  { t: "table", head: ["Quantity", "Value", "Note"], rows: [
    ["Core volume", "65.4 m³", "Large, as graphite requires"],
    ["Moderator-to-fuel ratio", "97,600", "Two orders above the water cases"],
    ["Critical mass", "24.9 kg U-235", "Very small — excellent neutron economy"],
    ["Moderator mass", "87.0 Mg graphite", "The core is mostly graphite"],
    ["Coolant mass in core", "0.00118 Mg", "Helium is almost weightless"],
    ["Thermal power", "6230 MWth", "400 K rise across the core"],
    ["Power density", "136 MW/m³", "Comparable to the PWR"],
    ["Heat flux", "95.2 W/cm²", "High — check against limits"],
    ["Coolant velocity", "438 m/s", "Mach limited"],
    ["Primary pump power", "145 MWe", "6.8 per cent of gross output"],
    ["Fuel temperature", "1300 K", "Acceptable for coated particle fuel"],
    ["Electrical power", "2131 MWe", "—"],
  ], widths: [3200, 2400, 2760], n: 7, cap: "Graphite-moderated, helium-cooled spherical core. The Primary page flags this case as Mach limited." },
  { t: "p", x: "Three results deserve comment." },
  { t: "p", x: "The moderator-to-fuel ratio of 97,600 is enormous, nearly a hundred times the light-water value. Graphite absorbs so few neutrons — 0.004 barns against water's 0.66 — that an extremely dilute fuel loading still achieves criticality. The consequence is a critical mass of only 24.9 kg in a 65 m³ core, the best neutron economy of any case in this manual. That is the fundamental attraction of graphite." },
  { t: "p", x: "The Primary page reports that the case is Mach limited. The requested flow of 3000 kg/s of helium through this channel array would exceed Mach 0.3 at 1000 K, so the program clips the velocity to the sonic limit and raises the system pressure to compensate. This is exactly what a real designer does — gas-cooled reactors operate at 40 to 70 atmospheres precisely to keep volumetric flow, and hence velocity, manageable." },
  { t: "p", x: "The pumping power of 145 MWe is the price. It consumes 6.8 per cent of the gross electrical output, against 0.25 per cent for the uprated PWR. Circulator power is the characteristic burden of gas cooling and it is why gas reactors need high pressure and large flow passages. Try raising the tube diameter from 1.2 cm to 2.5 cm and watch the pumping power collapse — at the cost of heat transfer area and therefore heat flux." },

  // ------------------------------------------------------------------ Ch 12
  { t: "h1", x: "12. Worked Example 4: An Open-Loop Propulsion Reactor" },
  { t: "p", x: "Nuclear thermal propulsion heats hydrogen directly in the core and expands it. There is no secondary circuit, no condenser, and no coolant recovery. Hydrogen is chosen because its very low molecular weight gives the highest exhaust velocity for a given temperature, and beryllium is a natural moderator for a compact core because it is a solid with a short Fermi age." },
  { t: "steps", x: [
    "Set the fuel to U-235 and the moderator to Be.",
    "Set the coolant to H2. The diagram switches to open loop.",
    "Set the geometry to Cylindrical, radius 40 cm and height 90 cm.",
    "Set maximum coolant temperature 2400 K, minimum 300 K.",
    "Set tube diameter 0.6 cm, porosity 0.50, flowrate 40 kg/s.",
  ]},
  { t: "fig", src: "fig10-openloop.png", w: 560, h: 343, n: 8, cap: "The system diagram for an open loop. The steam generator, condenser, and condensate pump are removed, and the coolant is exhausted rather than recovered." },
  { t: "table", head: ["Quantity", "Value", "Assessment"], rows: [
    ["Core volume", "0.452 m³", "Compact, as required"],
    ["Critical mass", "2.74 kg U-235", "Very small"],
    ["Moderator-to-fuel ratio", "7970", "Beryllium is a weak absorber"],
    ["Thermal power", "1200 MWth", "2100 K rise across the core"],
    ["Power density", "5310 MW/m³", "Extremely high"],
    ["Heat flux", "796 W/cm²", "Extremely high"],
    ["Coolant velocity", "1250 m/s", "Mach limited"],
    ["Maximum fuel temperature", "4570 K", "Above the melting point of any fuel"],
    ["Conversion", "36.0 per cent", "Fixed for the open loop"],
  ], widths: [3200, 2400, 2760], n: 8, cap: "An open-loop propulsion core. The fuel temperature result makes this design impossible as entered." },
  { t: "p", x: "The criticality result is excellent: 2.74 kg of U-235 in less than half a cubic metre. Beryllium is doing exactly what it should, providing moderation with almost no absorption in a compact solid." },
  { t: "p", x: "The thermal result is fatal. A maximum fuel temperature of 4570 K exceeds the melting point of uranium dioxide, about 3120 K, and of uranium carbide, about 2800 K. Even the refractory carbide fuels developed for the NERVA programme were limited to roughly 3000 K. This design would vaporise its own core." },
  { t: "p", x: "The exercise is to fix it, and the program shows you the levers. The centreline temperature rise scales with power density and with the square of the fuel radius. Reduce the tube diameter to 0.3 cm and the effective fuel radius halves, quartering the conduction term. Reduce the outlet temperature to 2000 K, which cuts both the power and the base temperature. Or enlarge the core, which cuts the power density directly. Try each in turn and watch which lever moves the number furthest — that habit of asking which variable dominates is the whole point of a parametric tool." },
  { t: "p", x: "Note also the coolant velocity of 1250 m/s, which the program has clipped to the Mach 0.3 limit for hydrogen at 2400 K. Hydrogen's sound speed at that temperature is enormous, which is why the clip lands so high, and it is the same physics that makes hydrogen the propellant of choice." },

  // ------------------------------------------------------------------ Ch 13
  { t: "h1", x: "13. Parametric Studies" },
  { t: "p", x: "Single cases teach little. What builds intuition is holding everything constant but one variable and watching the response. The Save case button collects designs into a comparison table so you can do this systematically." },

  { t: "h2", x: "13.1 Varying the moderator" },
  { t: "p", x: "Fix a 200 cm cube of U-235 with water coolant, and change only the moderator." },
  { t: "table", head: ["Moderator", "Fermi age τ (cm²)", "L² (cm²)", "σ_abs (barns)", "Nm/Nf", "Critical mass (kg)"], rows: [
    ["Light water, H₂O", "31.36", "7.62", "0.66", "1036", "100.8"],
    ["Heavy water, D₂O", "121", "10,000", "0.002", "384", "269.1"],
    ["Beryllium, Be", "84.64", "441", "0.01", "3632", "106.4"],
    ["Carbon-12", "350", "4121", "0.004", "796", "374.0"],
    ["Carbon-13", "350", "4121", "0.002", "807", "340.7"],
  ], widths: [2300, 1900, 1500, 1600, 1300, 1760], n: 9, cap: "Moderator comparison in a 200 cm cube of U-235, water cooled. Light water gives the lowest critical mass at this size; the graphites give the highest." },
  { t: "p", x: "Light water wins at this size, with the lowest critical mass, because its very short Fermi age and diffusion length keep the whole neutron economy compact. The graphites are worst, needing three and a half times the fuel, because their 350 cm² Fermi age lets neutrons wander far outside a 200 cm core while slowing down." },
  { t: "p", x: "Beryllium is the interesting case. It needs a moderator-to-fuel ratio of 3632, three and a half times water's, yet its critical mass is only slightly higher at 106.4 kg. The reason is that beryllium's mass number of 9 is half water's effective 18, so a given atom ratio corresponds to a much smaller mass ratio. This is why beryllium appears in compact reactors where its cost can be justified." },
  { t: "p", x: "Heavy water's result — 269 kg, worse than light water — is a consequence of core size, not of any deficiency. At 200 cm the core is small enough that heavy water's long diffusion length hurts. Enlarge the core and the ranking changes. That is a study worth running yourself." },

  { t: "h2", x: "13.2 Varying the fuel" },
  { t: "p", x: "Now fix the moderator at light water and vary the fuel." },
  { t: "table", head: ["Fuel", "σ_fission (barns)", "σ_absorption (barns)", "Nm/Nf", "Critical mass (kg)"], rows: [
    ["U-233", "514", "569", "868", "119.3"],
    ["U-235", "582", "679", "1036", "100.8"],
    ["Pu-239", "760", "1030", "1572", "67.6"],
    ["Pu-241", "988", "1384", "2112", "50.7"],
    ["Cm-245", "1700", "2000", "3052", "35.7"],
    ["Am-242", "6000", "7700", "11,749", "9.2"],
  ], widths: [1900, 2300, 2500, 1700, 1960], n: 10, cap: "Fuel comparison in a 200 cm cube moderated and cooled by light water. Critical mass falls monotonically with absorption cross section." },
  { t: "p", x: "The ordering follows the absorption cross section almost exactly. A fuel that absorbs thermal neutrons strongly needs fewer atoms present to capture the same number of neutrons, so the critical mass falls. Americium-242, with a thermal absorption cross section of 7700 barns, requires only 9.2 kg — an eleventh of the U-235 requirement." },
  { t: "p", x: "Treat that result with care. The program holds η at 2.06 for every fuel, which is the U-235 value; the real figures differ, and for Am-242 the difference matters. Am-242 is also intensely radioactive with a short half-life, exists in gram quantities worldwide, and could not be fabricated into fuel by any known process. The value of the comparison is in the trend, not the absolute number." },

  { t: "h2", x: "13.3 Varying the geometry" },
  { t: "p", x: "Section 4.3 showed that a sphere gives the smallest critical mass for a given volume. Repeat that study at several volumes and you will find the advantage grows as the core shrinks, because leakage is a surface effect and the surface-to-volume ratio dominates small cores. At 8 m³ the sphere saves less than one per cent over a cube; at 0.1 m³ the saving is substantial." },

  { t: "h2", x: "13.4 Suggested exercises" },
  { t: "numbers", x: [
    "Find the core size that minimises critical mass for Pu-239 in light water. Compare it with the 48 cm figure for U-235 and explain the difference.",
    "Hold thermal power at 2000 MWth and find the combination of flow rate and temperature rise that minimises pumping power. What limits you?",
    "For the graphite and helium design of Chapter 11, find the tube diameter that brings pumping power below 2 per cent of gross output. What happens to the heat flux?",
    "Using Define Your Own Fuel, model 4 per cent enriched uranium dioxide and compare the required mass with the pure U-235 result.",
    "Vary porosity from 0.1 to 0.7 in the uprated PWR of Chapter 9 and plot critical mass, heat flux, and pumping power against it. Where would you operate, and why?",
  ]},

  // ------------------------------------------------------------------ Ch 14
  { t: "h1", x: "14. When Criticality Fails" },
  { t: "p", x: "If your combination of materials and geometry cannot reach criticality, a warning banner appears across the top of the workspace and the affected results are marked." },
  { t: "fig", src: "fig9-warning.png", w: 624, h: 65, n: 9, cap: "The criticality warning. It appears immediately, and it names the three variables that will fix the problem." },
  { t: "p", x: "The mathematical signature is a negative moderator-to-fuel ratio. Recall the criticality condition from Section 4.1: the numerator contains the term η·exp(−B²τ) − 1. When the core is small, the buckling B² is large, the exponential is small, and that term goes negative. A negative numerator gives a negative ratio, which has no physical meaning. It is the calculation's way of saying that no amount of fuel will work, because neutrons are leaking out faster than fission can replace them." },
  { t: "p", x: "Three remedies exist, in order of effectiveness." },
  { t: "numbers", x: [
    "Enlarge the core. This reduces the buckling, which is the direct cause. For U-235 in light water, a cube must be at least about 35 cm on a side; below that no composition is critical. Changing to a spherical shape at the same volume also helps, because a sphere has the lowest buckling of any shape.",
    "Choose a moderator with a shorter Fermi age. The leakage term is exp(−B²τ), so τ and B² enter as a product. Switching from graphite at 350 cm² to light water at 31.4 cm² has the same effect on fast leakage as reducing the buckling elevenfold.",
    "Choose a fuel with a larger fission cross section. This raises the production side of the balance. Moving from U-235 to Pu-239 or Am-242 will rescue a design that light water cannot.",
  ]},
  { t: "p", x: "A fourth remedy exists in reality but not in this program: add a reflector. Surrounding the core with a layer of moderator scatters escaping neutrons back in, and it can reduce critical mass by a third or more. The program assumes a bare core throughout, so every critical mass it reports is conservative in that specific respect." },
];

// ---------------------------------------------------------------- Glossary
export const glossary = [
  { t: "h1", x: "Glossary" },
  { t: "gloss", x: [
    ["Absorption cross section", "The effective target area a nucleus presents to a neutron for absorption, measured in barns. Large values mean strong absorption."],
    ["Barn", "A unit of nuclear cross section equal to 10⁻²⁴ cm². Roughly the geometric cross section of a heavy nucleus."],
    ["Boiling water reactor (BWR)", "A reactor in which the coolant boils inside the core and the resulting steam drives the turbine directly, with no separate steam generator."],
    ["Buckling, geometric (B²)", "A measure of the curvature of the neutron flux, determined entirely by core shape and size, in cm⁻². Large buckling means high leakage."],
    ["Burnable poison", "A neutron absorber deliberately loaded into the core that is consumed as the core runs, offsetting fuel depletion and extending core life."],
    ["Burnup", "The energy extracted from a unit mass of fuel, or equivalently the fraction of heavy atoms fissioned. The program reports annual burnup in megagrams per year."],
    ["CANDU", "The Canadian heavy-water reactor, moderated and cooled by D₂O, capable of running on natural uranium."],
    ["Cladding", "The thin metal tube, usually zirconium alloy or stainless steel, that encloses the fuel and retains fission products."],
    ["Closed loop", "A power conversion arrangement in which the primary coolant transfers heat to a separate secondary fluid through a steam generator and is itself recirculated."],
    ["Critical", "The condition in which the neutron population is exactly steady, k_eff = 1. Says nothing about power level."],
    ["Critical mass", "The minimum mass of fissile fuel that sustains a chain reaction in a given geometry and composition."],
    ["Delayed neutrons", "Neutrons emitted 0.2 to 55 seconds after a fission, from the decay of certain fission products. About 0.65 per cent of the total for U-235; they make reactor control possible."],
    ["Departure from nucleate boiling (DNB)", "The transition from efficient nucleate boiling to film boiling, in which a vapour blanket insulates the surface and the wall temperature rises sharply. A hard limit on heat flux."],
    ["Diffusion length (L)", "The characteristic distance a thermal neutron travels before absorption. L² appears in the thermal leakage term."],
    ["Doppler broadening", "The widening of resonance absorption peaks as fuel temperature rises and nuclear thermal motion increases. A principal source of the negative temperature coefficient."],
    ["Enrichment", "The fraction of fissile isotope in a fuel, usually U-235 in uranium. Natural uranium is 0.72 per cent U-235."],
    ["Eta (η)", "The number of fission neutrons produced per thermal neutron absorbed in fuel. The program uses 2.06, the U-235 value, for all fuels."],
    ["Fast fission factor (ε)", "The ratio of total fission neutrons to those produced by thermal fission alone, accounting for fissions caused by fast neutrons."],
    ["Fermi age (τ)", "One sixth of the mean square distance a neutron travels from birth to thermalisation, in cm². Controls fast leakage through the term exp(−B²τ)."],
    ["Fissile", "Capable of fission by neutrons of any energy, including thermal. U-233, U-235, Pu-239, and Pu-241 are the practical fissile nuclides."],
    ["Fission", "The splitting of a heavy nucleus into two fragments, releasing one to three neutrons, gamma rays, and about 200 MeV."],
    ["Fission products", "The nuclides produced by fission and their decay chains. Some, notably xenon-135, are strong neutron absorbers."],
    ["Flux, neutron", "The number of neutrons crossing unit area per unit time, in neutrons per second per cm². Determines reaction rates."],
    ["Heat flux", "Thermal power per unit of heat transfer surface, in W/cm². Limited by departure from nucleate boiling."],
    ["Homogeneous reactor", "An idealisation in which fuel and moderator are uniformly mixed rather than arranged in discrete elements. Used throughout this program."],
    ["Hot channel factor", "The ratio of conditions in the most limiting coolant channel to the core average, typically 2 to 2.5 in a large core."],
    ["HTGR", "High-temperature gas reactor. Graphite moderated, helium cooled, capable of outlet temperatures far above water reactors."],
    ["k-effective (k_eff)", "The effective multiplication factor, the ratio of neutrons in one generation to those in the previous one."],
    ["Leakage", "Loss of neutrons through the core surface. Divided into fast leakage during slowing down and thermal leakage during diffusion."],
    ["MAGNOX", "The early British gas-cooled reactor type, named for its magnesium alloy cladding, fuelled with natural uranium metal."],
    ["Moderator", "A material that slows fast neutrons to thermal energy through elastic scattering, chosen for low mass number and low absorption."],
    ["Moderator-to-fuel ratio (Nm/Nf)", "The number of moderator atoms per fuel atom. The quantity this program solves for. Has an optimum: too low is under-moderated, too high is over-moderated."],
    ["Open loop", "A power conversion arrangement in which the coolant expands through the turbine directly and is discarded. Used in propulsion reactors."],
    ["Porosity (ε)", "The fraction of core volume occupied by coolant. Also called void fraction. Sets channel count and solid volume."],
    ["Power density", "Thermal power per unit of core volume, in MW/m³. A key measure of how hard a core is working."],
    ["Pressurised water reactor (PWR)", "A reactor in which water is held above saturation pressure so it does not boil, and transfers heat to a separate steam circuit."],
    ["Prompt neutrons", "Neutrons emitted essentially instantly at fission, about 10⁻⁴ seconds. The great majority of all fission neutrons."],
    ["Reactivity (ρ)", "A measure of departure from criticality, ρ = 1 − 1/k_eff. Zero at critical."],
    ["Reflector", "A layer of moderating material surrounding the core that scatters escaping neutrons back in, reducing critical mass. Not modelled here."],
    ["Resonance escape probability (p)", "The fraction of neutrons that slow past the resonance absorption region without being captured."],
    ["Reynolds number (Re)", "The dimensionless ratio of inertial to viscous forces in a flow. Above about 4000 the flow is turbulent."],
    ["Scram", "The rapid insertion of all control rods, completing in about one second, to shut the reactor down."],
    ["Specific power", "Thermal power per unit mass of fuel, in kW per gram."],
    ["Subcritical", "k_eff below one; the neutron population declines."],
    ["Supercritical", "k_eff above one; the neutron population grows."],
    ["Thermal neutron", "A neutron in thermal equilibrium with its surroundings, about 0.025 eV at room temperature."],
    ["Thermal utilisation (f)", "The fraction of absorbed thermal neutrons that are absorbed in fuel rather than in moderator, coolant, or structure."],
    ["Xenon poisoning", "The build-up of xenon-135, an extremely strong thermal absorber, after a power reduction. Produces a dead time during which restart is impossible."],
  ]},
];

// -------------------------------------------------------------- References
export const references = [
  { t: "h1", x: "References" },
  { t: "h2", x: "Reactor physics and design" },
  { t: "refs", x: [
    "Glasstone, S., and A. Sesonske. Nuclear Reactor Engineering, 4th ed. New York: Chapman & Hall, 1994.",
    "Lamarsh, J. R., and A. J. Baratta. Introduction to Nuclear Engineering, 3rd ed. Upper Saddle River: Prentice Hall, 2001.",
    "Duderstadt, J. J., and L. J. Hamilton. Nuclear Reactor Analysis. New York: Wiley, 1976.",
    "Weinberg, A. M., and E. P. Wigner. The Physical Theory of Neutron Chain Reactors. Chicago: University of Chicago Press, 1958.",
    "Glasstone, S., and M. C. Edlund. The Elements of Nuclear Reactor Theory. New York: Van Nostrand, 1952.",
    "Bell, G. I., and S. Glasstone. Nuclear Reactor Theory. New York: Van Nostrand Reinhold, 1970.",
    "Knief, R. A. Nuclear Engineering: Theory and Technology of Commercial Nuclear Power, 2nd ed. Washington: Taylor & Francis, 1992.",
  ]},
  { t: "h2", x: "Thermal-hydraulics and heat transfer" },
  { t: "refs", x: [
    "Todreas, N. E., and M. S. Kazimi. Nuclear Systems I: Thermal Hydraulic Fundamentals, 2nd ed. Boca Raton: CRC Press, 2011.",
    "El-Wakil, M. M. Nuclear Heat Transport. La Grange Park: American Nuclear Society, 1978.",
    "Tong, L. S., and J. Weisman. Thermal Analysis of Pressurized Water Reactors, 3rd ed. La Grange Park: American Nuclear Society, 1996.",
    "Rust, J. H. Nuclear Power Plant Engineering. Buchanan: Haralson Publishing, 1979.",
  ]},
  { t: "h2", x: "Nuclear data" },
  { t: "refs", x: [
    "Mughabghab, S. F. Atlas of Neutron Resonances, 5th ed. Amsterdam: Elsevier, 2006.",
    "Chadwick, M. B., et al. \"ENDF/B-VII.1 Nuclear Data for Science and Technology.\" Nuclear Data Sheets 112, no. 12 (2011): 2887–2996.",
    "Etherington, H., ed. Nuclear Engineering Handbook. New York: McGraw-Hill, 1958.",
    "International Atomic Energy Agency. Nuclear Power Reactors in the World. Reference Data Series No. 2. Vienna: IAEA, published annually.",
  ]},
  { t: "h2", x: "The program" },
  { t: "refs", x: [
    "Alesso, H. P. Design Your Own Nuclear Reactor. Microsoft Visual Basic 3 for Windows 3.1, 1993. Original source in the project repository.",
    "Design Your Own Nuclear Reactor, browser edition. https://reactor-seven.vercel.app/",
    "Project repository, including the 1993 sources. https://github.com/alessoh/reactor",
    "United States Nuclear Regulatory Commission. Glossary. https://www.nrc.gov/reading-rm/basic-ref/glossary.html",
  ]},
];
